uncomment all steps and remove uneeded commands

diff --git a/.github/workflows/deploy-backend.yaml b/.github/workflows/deploy-backend.yaml
--- a/.github/workflows/deploy-backend.yaml
+++ b/.github/workflows/deploy-backend.yaml
@@ -46,15 +46,15 @@ jobs:
           mkdir reports
           npm audit --omit=dev --audit-level=${{ inputs.audit-level }} | tee reports/npm_audit.output
 
-#      - name: ⚒️ Build project
-#        id: npm-compile
-#        run: npm run compile-no-emit
+      - name: ⚒️ Build project
+        id: npm-compile
+        run: npm run compile-no-emit
 
-#      - name: 🧪️ Execute unit tests
-#        id: npm-test
-#        run: |
-#          mkdir -p reports
-#          npm run test:jasmine-coverage | tee reports/unit_tests.output
+      - name: 🧪️ Execute unit tests
+        id: npm-test
+        run: |
+          mkdir -p reports
+          npm run test:jasmine-coverage | tee reports/unit_tests.output
 
       - name: 🔑 Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v3
@@ -68,96 +68,96 @@ jobs:
           secret-ids: des-globals/env
           parse-json-secrets: true
 
-#      - name: 📦 Package for Lambda
-#        id: npm-package
-#        run: npm run package
-#
-#      - name: ☁️ Upload to GitHub Summary
-#        uses: actions/upload-artifact@v3
-#        with:
-#          name: '${{env.SERVICE_NAME}}-artefacts-${{github.run_id}}'
-#          path: |
-#            artefacts/*
-#            reports/*
-#          retention-days: 3
+      - name: 📦 Package for Lambda
+        id: npm-package
+        run: npm run package
 
-  #      - name: ☁️ Upload to S3
-  #        id: s3-upload-artefacts
-  #        run: |
-  #          echo "## Artefacts:" >> $GITHUB_STEP_SUMMARY
-  #          for artefact in "artefacts"/*; do
-  #            aws s3 cp "$artefact" \
-  #            s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/functions/"${artefact#artefacts/}"
-  #            echo "✅ Uploaded ${artefact#artefacts/} to S3" >> $GITHUB_STEP_SUMMARY
-  #          done
-  #
-  #      - name: ☁️️ Manifest
-  #        id: create_manifest
-  #        run: |
-  #          version=$(jq -r ".version" < package.json | cut -d . -f 1,2)
-  #          file_name="${{env.SERVICE_NAME}}_${version}.$(date +%s).manifest"
-  #          echo "file_name=${file_name}" >> $GITHUB_OUTPUT
-  #
-  #          for func in $(yq eval '.functions | keys' -o=json serverless.yml | jq -r '.[]'); do
-  #            function_version=$(aws s3 ls \
-  #            ${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/functions/"$func" \
-  #            | sort -r | head -n 1 | cut -d '-' -f 4-)
-  #
-  #            echo "${func}_version = ${function_version}" >> $file_name
-  #          done
-  #
-  #          aws s3 cp $file_name s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/releases/
-  #          echo "## Manifests:" >> $GITHUB_STEP_SUMMARY
-  #          echo "✅ Uploaded $file_name to S3" >> $GITHUB_STEP_SUMMARY
-  #
-  #      - name: ☁️ Upload Test Reports to S3
-  #        id: s3-upload-reports
-  #        run: |
-  #          name=${{steps.create_manifest.outputs.file_name}}
-  #          FILE="TestReports-${name/"manifest"/"zip"}"
-  #          zip -r $FILE reports/
-  #          aws s3 cp $FILE \
-  #          s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/microservices/${{env.SERVICE_NAME}}/test-reports/
-  #          echo "## Reports" >> $GITHUB_STEP_SUMMARY
-  #          echo "✅ Uploaded ${FILE} to S3" >> $GITHUB_STEP_SUMMARY
-  #
-  #      - name: 🔑 Configure NonProd AWS Credentials
-  #        uses: aws-actions/configure-aws-credentials@v3
-  #        with:
-  #          role-to-assume: arn:aws:iam::${{ secrets.AWS_NONPROD_ACCOUNT_ID }}:role/github-actions
-  #          aws-region: ${{ secrets.DVSA_AWS_REGION }}
-  #
-  #      - name: 🚀 Deploy Lambda Package
-  #        id: deploy-lambda-package
-  #        run: |
-  #          echo "## Deployments:" >> $GITHUB_STEP_SUMMARY
-  #          for func in $(yq eval '.functions | keys' -o=json serverless.yml | jq -r '.[]'); do
-  #            artefact_file_name=$(find artefacts -type f -name ${func}*)
-  #            lambda_function_name=$(aws lambda list-functions \
-  #            --query "Functions[?starts_with(FunctionName, 'mes-dev-${{ inputs.component }}') \
-  #            && Handler == '${func}.handler'].FunctionName" | jq -r '.[]')
-  #
-  #            if [[ -z $lambda_function_name ]]; then
-  #              echo "No equivalent Lambda function found for ${func}. Deployment aborted."
-  #              exit 1
-  #            fi
-  #
-  #            aws lambda update-function-code --function-name $lambda_function_name \
-  #            --zip-file fileb://${artefact_file_name} \
-  #            --query "{FunctionName: FunctionName, LastUpdateStatus: LastUpdateStatus}"
-  #
-  #            aws lambda wait function-updated --function-name $lambda_function_name
-  #            status=$(aws lambda get-function-configuration --function-name $lambda_function_name \
-  #            --query "LastUpdateStatus" --output text)
-  #
-  #            if [ $status == "Failed" ]; then
-  #              echo "Failed to update ${lambda_function_name}."
-  #              exit 1
-  #            fi
-  #
-  #            echo "Successfully updated ${lambda_function_name}."
-  #            echo "✅ Deployed $artefact_file_name to Lambda" >> $GITHUB_STEP_SUMMARY
-  #          done
+      - name: ☁️ Upload to GitHub Summary
+        uses: actions/upload-artifact@v3
+        with:
+          name: '${{env.SERVICE_NAME}}-artefacts-${{github.run_id}}'
+          path: |
+            artefacts/*
+            reports/*
+          retention-days: 3
+
+      - name: ☁️ Upload to S3
+        id: s3-upload-artefacts
+        run: |
+          echo "## Artefacts:" >> $GITHUB_STEP_SUMMARY
+          for artefact in "artefacts"/*; do
+            aws s3 cp "$artefact" \
+            s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/functions/"${artefact#artefacts/}"
+            echo "✅ Uploaded ${artefact#artefacts/} to S3" >> $GITHUB_STEP_SUMMARY
+          done
+
+      - name: ☁️️ Manifest
+        id: create_manifest
+        run: |
+          version=$(jq -r ".version" < package.json | cut -d . -f 1,2)
+          file_name="${{env.SERVICE_NAME}}_${version}.$(date +%s).manifest"
+          echo "file_name=${file_name}" >> $GITHUB_OUTPUT
+
+          for func in $(yq eval '.functions | keys' -o=json serverless.yml | jq -r '.[]'); do
+            function_version=$(aws s3 ls \
+            ${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/functions/"$func" \
+            | sort -r | head -n 1 | cut -d '-' -f 4-)
+
+            echo "${func}_version = ${function_version}" >> $file_name
+          done
+
+          aws s3 cp $file_name s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/releases/
+          echo "## Manifests:" >> $GITHUB_STEP_SUMMARY
+          echo "✅ Uploaded $file_name to S3" >> $GITHUB_STEP_SUMMARY
+
+      - name: ☁️ Upload Test Reports to S3
+        id: s3-upload-reports
+        run: |
+          name=${{steps.create_manifest.outputs.file_name}}
+          FILE="TestReports-${name/"manifest"/"zip"}"
+          zip -r $FILE reports/
+          aws s3 cp $FILE \
+          s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/microservices/${{env.SERVICE_NAME}}/test-reports/
+          echo "## Reports" >> $GITHUB_STEP_SUMMARY
+          echo "✅ Uploaded ${FILE} to S3" >> $GITHUB_STEP_SUMMARY
+
+      - name: 🔑 Configure NonProd AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_NONPROD_ACCOUNT_ID }}:role/github-actions
+          aws-region: ${{ secrets.DVSA_AWS_REGION }}
+
+      - name: 🚀 Deploy Lambda Package
+        id: deploy-lambda-package
+        run: |
+          echo "## Deployments:" >> $GITHUB_STEP_SUMMARY
+          for func in $(yq eval '.functions | keys' -o=json serverless.yml | jq -r '.[]'); do
+            artefact_file_name=$(find artefacts -type f -name ${func}*)
+            lambda_function_name=$(aws lambda list-functions \
+            --query "Functions[?starts_with(FunctionName, 'mes-dev-${{ inputs.component }}') \
+            && Handler == '${func}.handler'].FunctionName" | jq -r '.[]')
+
+            if [[ -z $lambda_function_name ]]; then
+              echo "No equivalent Lambda function found for ${func}. Deployment aborted."
+              exit 1
+            fi
+
+            aws lambda update-function-code --function-name $lambda_function_name \
+            --zip-file fileb://${artefact_file_name} \
+            --query "{FunctionName: FunctionName, LastUpdateStatus: LastUpdateStatus}"
+
+            aws lambda wait function-updated --function-name $lambda_function_name
+            status=$(aws lambda get-function-configuration --function-name $lambda_function_name \
+            --query "LastUpdateStatus" --output text)
+
+            if [ $status == "Failed" ]; then
+              echo "Failed to update ${lambda_function_name}."
+              exit 1
+            fi
+
+            echo "Successfully updated ${lambda_function_name}."
+            echo "✅ Deployed $artefact_file_name to Lambda" >> $GITHUB_STEP_SUMMARY
+          done
 
       - name: Set Outputs
         if: always()
@@ -194,8 +194,7 @@ jobs:
           secret-ids: des-globals/env
           parse-json-secrets: true
 
-      - name: 🧐 SonarQube Scan
-        id: sonarqube-scan
+      - name: ⚙️ Configure SonarQube Properties
         run: |
           cat <<EOF > sonar-project.properties
           sonar.projectKey=mes-${{ env.SERVICE_NAME }}-service
@@ -206,15 +205,9 @@ jobs:
           sonar.typescript.lcov.reportPaths=coverage/lcov.info
           EOF
 
-#          npm run sonar-scanner
-
-#          export SONAR_TOKEN=${{ env.DES_GLOBALS_ENV_SONAR_TOKEN }}
-#
-#          sonar-scanner \
-#          -Dsonar.host.url=${{ env.DES_GLOBALS_ENV_SONAR_HOST_URL }} \
-#          -Dsonar.sources=src \
-#          -Dsonar.exclusions=src/**/__tests__/**/*,src/**/__mocks__/**/* \
-#          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
+      - name: 🧐 SonarQube Scan
+        id: sonarqube-scan
+        run: npm run sonar-scanner
 
       - name: Set Outputs
         if: always()
