amend upload to s3 job and add deploy job

diff --git a/.github/workflows/deploy-backend-des.yaml b/.github/workflows/deploy-backend-des.yaml
--- a/.github/workflows/deploy-backend-des.yaml
+++ b/.github/workflows/deploy-backend-des.yaml
@@ -18,24 +18,29 @@ permissions:
 
 jobs:
   build:
-    name: Build
+    name: 🧱 Build
     uses: dvsa/appdev-github-actions/.github/workflows/ci-backend.yaml@main
     secrets: inherit
 
-  push:
-    name: Push
+  upload-artifacts:
+    name: ☁️ Upload Artifacts to S3
     needs: build
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v4
+      - name: 📨 Checkout
+        uses: actions/checkout@v4
         with:
           ref: ${{ github.ref_name }}
 
-      - name: 🔍 Determine service name
+      - name: ⚙️ Set Environment Variables
         shell: bash
-        run: echo "SERVICE_NAME=$(jq -r '.name | sub("^(mes|des)-"; "") | sub ("-service"; "")' package.json)" >> $GITHUB_ENV
+        run: |        
+          echo "SERVICE_NAME=$(jq -r '.name | sub("mes-"; "") | sub ("-service"; "")' package.json)" >> $GITHUB_ENV
+          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
+          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
 
-      - name: 🪪 Get Credentials
+      - name: 🪪 Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: ${{ secrets.DES_MGMT_ROLE }}
@@ -54,33 +59,97 @@ jobs:
           name: ${{ github.event.repository.name }}-artifacts-${{ github.event.pull_request.number || github.run_id }}
           path: artifacts
 
-      - name: ☁️ Upload to S3
+      - name: ☁️ Upload Artifacts to S3
         id: s3-upload-artefacts
         run: |
-          short_sha=$(echo ${{ github.sha }} | cut -c1-7)
-          echo "## Artifacts:" >> $GITHUB_STEP_SUMMARY
-          for artifact in "artifacts"/*; do
-            filename="$(basename $artifact '.zip')-$short_sha.zip"
-          
-            aws s3 cp "$artifact" \
-            s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/functions/$filename
+          echo "## Functions:" >> $GITHUB_STEP_SUMMARY    
+          manifest="${{ env.SERVICE_NAME }}_${{ env.VERSION }}-$(date +%s)-${{ env.SHORT_SHA }}.manifest"
 
-            echo "✅ Uploaded ${artifact#artifacts/} to S3" >> $GITHUB_STEP_SUMMARY
+          for artifact in artifacts/*; do
+            artifact_filename="$(basename $artifact '.zip')-${{ env.SHORT_SHA }}.zip"
+            
+            # Upload function to S3
+            aws s3 cp $artifact s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/functions/$artifact_filename
+            echo "✅ Uploaded '$artifact_filename' to S3" >> $GITHUB_STEP_SUMMARY
+          
+            # Add function to manifest
+            function_name="$(echo ${artifact_filename%%-${{ env.VERSION }}*} | tr '-' '_')"
+            echo "${function_name}_filename = \"$artifact_filename\"" >> "$manifest"
           done
           
-          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
-          echo "GIT_REV=$short_sha" >> $GITHUB_ENV
-
-      - name: ☁️️ Manifest
-        if: ${{ !startsWith(inputs.branch, 'release-') }}
-        id: create_manifest
-        run: |
-          file_name="${{ env.SERVICE_NAME }}_${{ env.VERSION }}-${{ env.GIT_REV }}.manifest"
-          for func in $(yq eval '.functions | keys' -o=json serverless.yml | jq -r '.[]'); do
-            echo "${func}_version = \"${{ env.VERSION }}-${{ env.GIT_REV }}.zip\"" >> $file_name
-          done
-
-          aws s3 cp $file_name s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/manifests/dev/
+          # Upload manifest to S3
+          aws s3 cp $manifest s3://${{ env.DES_GLOBALS_ENV_ARTEFACT_S3 }}/mes/gha/manifests/dev/
 
           echo "## Manifests:" >> $GITHUB_STEP_SUMMARY
-          echo "✅ Uploaded $file_name to S3" >> $GITHUB_STEP_SUMMARY
+          echo "✅ Uploaded '$manifest' to S3" >> $GITHUB_STEP_SUMMARY
+
+  deploy:
+    name: 🚀 Deploy
+    needs: [build, upload-artifacts]
+    if: ${{ !startsWith(inputs.branch, 'release-') }}
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: 📨 Checkout
+        uses: actions/checkout@v4
+
+      - name: ⚙️ Set Environment Variables
+        shell: bash
+        run: |
+          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
+          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
+
+      - name: 📥 Download Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ github.event.repository.name }}-artifacts-${{ github.event.pull_request.number || github.run_id }}
+          path: artifacts
+
+      - name: 🪪 Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.DES_MGMT_ROLE }}
+          aws-region: ${{ vars.DVSA_AWS_REGION}}
+          role-session-name: GHA
+
+      - name: 🪪 Configure NonProd AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          role-to-assume: ${{ secrets.DES_NONPROD_ROLE }}
+          aws-region: ${{ secrets.DVSA_AWS_REGION }}
+
+      - name: 🚀 Deploy Lambda Package
+        id: deploy-lambda-package
+        run: |
+          echo "## Deployments:" >> $GITHUB_STEP_SUMMARY       
+          lambda_functions=$(aws lambda list-functions --query "Functions[?starts_with(FunctionName, 'mes-dev-api')].FunctionName" --output text | tr '\t' '\n')
+          
+          for artifact in artifacts/*; do
+            artifact_filename="$(basename $artifact '.zip')-${{ env.SHORT_SHA }}.zip"
+            function_name="${artifact_filename%%-${{ env.VERSION }}*}"
+          
+            # Find matching Lambda function using function name
+            pattern=$(echo $function_name | sed 's/-/\/ \&\& \//g')
+            lambda_function_name=$(echo "$lambda_functions" | awk "/$pattern/")
+          
+            if [[ -z $lambda_function_name ]]; then
+              echo "Deployment aborted: No equivalent Lambda function found for $function_name"
+              exit 1
+            fi    
+          
+            aws lambda update-function-code --function-name $lambda_function_name \
+            --zip-file fileb://artifacts/artifact_filename \
+            --query "{FunctionName: FunctionName, LastUpdateStatus: LastUpdateStatus}"
+          
+            aws lambda wait function-updated --function-name $lambda_function_name
+            status=$(aws lambda get-function-configuration --function-name $lambda_function_name \
+            --query "LastUpdateStatus" --output text)
+          
+            if [ $status == "Failed" ]; then
+              echo "Failed to update ${lambda_function_name}."
+              exit 1
+            fi
+          
+            echo "Successfully updated ${lambda_function_name}"
+            echo "✅ Deployed '$artifact_filename' to Lambda function '$lambda_function_name'" >> $GITHUB_STEP_SUMMARY
+          done
