separate deploy step into own job; download artifacts output from build job

diff --git a/.github/workflows/deploy-backend.yaml b/.github/workflows/deploy-backend.yaml
--- a/.github/workflows/deploy-backend.yaml
+++ b/.github/workflows/deploy-backend.yaml
@@ -23,9 +23,10 @@ permissions:
   contents: write
 
 jobs:
-  run-deploy:
+  build:
     runs-on: ubuntu-latest
     outputs:
+      service-name: ${{ steps.set-outputs.outputs.service-name }}
       job-context: ${{ steps.set-outputs.outputs.job-context }}
       steps-context: ${{ steps.set-outputs.outputs.steps-context }}
 
@@ -79,6 +80,7 @@ jobs:
           path: |
             artefacts/*
             reports/*
+            coverage/*
           retention-days: 3
 
       - name: ☁️ Upload to S3
@@ -121,52 +123,16 @@ jobs:
           echo "## Reports" >> $GITHUB_STEP_SUMMARY
           echo "✅ Uploaded ${FILE} to S3" >> $GITHUB_STEP_SUMMARY
 
-      - name: 🔑 Configure NonProd AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v3
-        with:
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_NONPROD_ACCOUNT_ID }}:role/github-actions
-          aws-region: ${{ secrets.DVSA_AWS_REGION }}
-
-      - name: 🚀 Deploy Lambda Package
-        id: deploy-lambda-package
-        run: |
-          echo "## Deployments:" >> $GITHUB_STEP_SUMMARY
-          for func in $(yq eval '.functions | keys' -o=json serverless.yml | jq -r '.[]'); do
-            artefact_file_name=$(find artefacts -type f -name ${func}*)
-            lambda_function_name=$(aws lambda list-functions \
-            --query "Functions[?starts_with(FunctionName, 'mes-dev-${{ inputs.component }}') \
-            && Handler == '${func}.handler'].FunctionName" | jq -r '.[]')
-
-            if [[ -z $lambda_function_name ]]; then
-              echo "No equivalent Lambda function found for ${func}. Deployment aborted."
-              exit 1
-            fi
-
-            aws lambda update-function-code --function-name $lambda_function_name \
-            --zip-file fileb://${artefact_file_name} \
-            --query "{FunctionName: FunctionName, LastUpdateStatus: LastUpdateStatus}"
-
-            aws lambda wait function-updated --function-name $lambda_function_name
-            status=$(aws lambda get-function-configuration --function-name $lambda_function_name \
-            --query "LastUpdateStatus" --output text)
-
-            if [ $status == "Failed" ]; then
-              echo "Failed to update ${lambda_function_name}."
-              exit 1
-            fi
-
-            echo "Successfully updated ${lambda_function_name}."
-            echo "✅ Deployed $artefact_file_name to Lambda" >> $GITHUB_STEP_SUMMARY
-          done
-
       - name: ➡️ Set Outputs
         if: always()
         id: set-outputs
         run: |
+          echo service-name=${{ env.SERVICE_NAME }} >> $GITHUB_OUTPUT
           echo job-context=$(echo '${{ toJSON(job) }}' | jq -c) >> $GITHUB_OUTPUT
           echo steps-context=$(echo '${{ toJSON(steps) }}' | jq -c) >> $GITHUB_OUTPUT
 
-  run-sonar-scan:
+  sonar-scan:
+    needs: build
     runs-on: mito-2
     outputs:
       job-context: ${{ steps.set-outputs.outputs.job-context }}
@@ -175,6 +141,11 @@ jobs:
     steps:
       - name: 📨 Checkout
         uses: actions/checkout@v3
+
+      - name: ☁️ Download Artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: '${{needs.build.outputs.service-name}}-artefacts-${{github.run_id}}'
 
       - name: ⚙️ Set Up Node
         id: node-setup
@@ -216,9 +187,76 @@ jobs:
           echo job-context=$(echo '${{ toJSON(job) }}' | jq -c) >> $GITHUB_OUTPUT
           echo steps-context=$(echo '${{ toJSON(steps) }}' | jq -c) >> $GITHUB_OUTPUT
 
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    outputs:
+      job-context: ${{ steps.set-outputs.outputs.job-context }}
+      steps-context: ${{ steps.set-outputs.outputs.steps-context }}
+
+    steps:
+      - name: 📨 Checkout
+        uses: actions/checkout@v3
+
+      - name: ☁️ Download Artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: '${{needs.build.outputs.service-name}}-artefacts-${{github.run_id}}'
+
+      - name: 🔑 Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
+          aws-region: ${{ secrets.DVSA_AWS_REGION }}
+
+      - name: 🔑 Configure NonProd AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_NONPROD_ACCOUNT_ID }}:role/github-actions
+          aws-region: ${{ secrets.DVSA_AWS_REGION }}
+
+      - name: 🚀 Deploy Lambda Package
+        id: deploy-lambda-package
+        run: |
+          echo "## Deployments:" >> $GITHUB_STEP_SUMMARY
+          for func in $(yq eval '.functions | keys' -o=json serverless.yml | jq -r '.[]'); do
+            artefact_file_name=$(find artefacts -type f -name ${func}*)
+            lambda_function_name=$(aws lambda list-functions \
+            --query "Functions[?starts_with(FunctionName, 'mes-dev-${{ inputs.component }}') \
+            && Handler == '${func}.handler'].FunctionName" | jq -r '.[]')
+  
+            if [[ -z $lambda_function_name ]]; then
+              echo "No equivalent Lambda function found for ${func}. Deployment aborted."
+              exit 1
+            fi
+  
+            aws lambda update-function-code --function-name $lambda_function_name \
+            --zip-file fileb://${artefact_file_name} \
+            --query "{FunctionName: FunctionName, LastUpdateStatus: LastUpdateStatus}"
+  
+            aws lambda wait function-updated --function-name $lambda_function_name
+            status=$(aws lambda get-function-configuration --function-name $lambda_function_name \
+            --query "LastUpdateStatus" --output text)
+  
+            if [ $status == "Failed" ]; then
+              echo "Failed to update ${lambda_function_name}."
+              exit 1
+            fi
+  
+            echo "Successfully updated ${lambda_function_name}."
+            echo "✅ Deployed $artefact_file_name to Lambda" >> $GITHUB_STEP_SUMMARY
+          done
+
+      - name: ➡️ Set Outputs
+        if: always()
+        id: set-outputs
+        run: |
+          echo job-context=$(echo '${{ toJSON(job) }}' | jq -c) >> $GITHUB_OUTPUT
+          echo steps-context=$(echo '${{ toJSON(steps) }}' | jq -c) >> $GITHUB_OUTPUT
+
   send-teams-notification:
     if: always()
-    needs: [run-deploy, run-sonar-scan]
+    needs: [build, sonar-scan, deploy]
     runs-on: ubuntu-latest
     steps:
       - name: 📝 Generate MS Teams Notify JSON
@@ -232,5 +270,6 @@ jobs:
         with:
           webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
           job: ${{ steps.ms-teams-json.outputs.job-context }}
+          needs: ${{ toJson(needs) }}
           steps: ${{ steps.ms-teams-json.outputs.steps-context }}
           overwrite: "{title: `${{github.repository}} | ${{github.workflow}} | BY: ${{github.actor}}`}"
