split create/delete actions; add undo release cut workflow

diff --git a/.github/workflows/release-cut.yaml b/.github/workflows/release-cut.yaml
--- a/.github/workflows/release-cut.yaml
+++ b/.github/workflows/release-cut.yaml
@@ -2,16 +2,16 @@ name: ✂️ Release Cut
 on:
   workflow_call:
     inputs:
-      create-release-tag:
+      base-branch:
+        type: string
+        required: false
+      release-branch:
         type: string
         required: true
       create-release-branch:
         type: string
         required: true
-      base-branch:
-        type: string
-        required: false
-      release-branch:
+      create-release-tag:
         type: string
         required: true
       release-type:
@@ -29,20 +29,18 @@ jobs:
     env:
       GH_TOKEN: ${{ secrets.GH_TOKEN_TEMP }}
     steps:
-      - name: Validate Release Branch
+      - name: ✔️ Validate Inputs
+        id: validate_release_tag
         run: |
           if [[ ! "${{ inputs.release-branch }}" =~ ^release-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "❌ Invalid Release Branch '${{ inputs.release-branch }}'. Branch should be in the format release-x.x.x"
+            echo "❌ Invalid Release Branch: ${{ inputs.release-branch }}"
             exit 1
           fi
 
-# INSERT CHECH FOR BRANCH EXIST??
-
-      - name: 🔍 Get Branch
-        id: get_branch
-        shell: bash
-        run: |
-          echo "branch=$(echo ${{ inputs.release-tag }} | cut -d '.' -f -3)" >> $GITHUB_OUTPUT
+          if [[ ! "${{ inputs.base-branch }}" =~ ^release-[0-9]+\.[0-9]+\.[0-9]+$ ]] && [[ "${{ inputs.base-branch }}" != "default" ]]; then
+            echo "❌ Invalid Base Branch: ${{ inputs.base-branch }}"
+            exit 1
+          fi
 
       - name: 🔑 Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -54,28 +52,24 @@ jobs:
         id: get_repositories
         run: |
           aws secretsmanager get-secret-value --secret-id des-repositories --query SecretString | jq . --raw-output  > repositories.json
-          echo "repositories=$(cat repositories.json | jq -rc)" >> $GITHUB_OUTPUT
           
           [ "${{ inputs.release-type }}" == "full" ] && release_type="frontend backend" || release_type=${{ inputs.release-type }}
           echo "release_type=$release_type" >> $GITHUB_OUTPUT
 
       - name: ✨ Create Release Branch
-        if: ${{ inputs.create-release-branch == 'true' }}
-        uses: dvsa/des-workflow-actions/.github/actions/git-functions/manage-branches@main
+        if: inputs.create-release-branch == 'true'
+        uses: dvsa/des-workflow-actions/.github/actions/git-functions/create-branches@main
         with:
-          action: Create
           base-branch: ${{ inputs.base-branch }}
-          branch-name: ${{ steps.get_branch.outputs.branch }}
-          repositories: repositories.json
+          branch-name: ${{ inputs.release-branch }}
+          repos-json-filename: repositories.json
           release-type: ${{ steps.get_repositories.outputs.release_type }}
 
       - name: ✨ Create Release Tag
-        if: ${{ inputs.create-release-tag == 'true' }}
-        uses: dvsa/des-workflow-actions/.github/actions/git-functions/manage-tags@main
+        if: inputs.create-release-tag == 'true'
+        uses: dvsa/des-workflow-actions/.github/actions/git-functions/create-releases@main
         with:
-          action: Create
           base-branch: ${{ inputs.base-branch }}
-          branch-name: ${{ steps.get_branch.outputs.branch }}
-          repositories: ${{ steps.get_repositories.outputs.repositories }}
+          branch-name: ${{ inputs.release-branch }}
+          repos-json-filename: repositories.json
           release-type: ${{ steps.get_repositories.outputs.release_type }}
-
