remove validation for 4.35.0 release

diff --git a/.github/workflows/release-cut.yaml b/.github/workflows/release-cut.yaml
--- a/.github/workflows/release-cut.yaml
+++ b/.github/workflows/release-cut.yaml
@@ -44,15 +44,15 @@ jobs:
       frontend-release-tag: ${{ steps.create-release-tag.outputs.frontend-release-tag }}
       backend-release-tag: ${{ steps.create-release-tag.outputs.backend-release-tag }}
     steps:
-      - name: ✔️ Validate Inputs
-        run: |
-          pattern="^release-[0-9]+\.[0-9]+\.[0-9]+$"
-          
-          if [[ ! "${{ inputs.release-branch }}" =~ $pattern ]] || \
-          [[ ! "${{ inputs.base-branch }}" =~ $pattern && "${{ inputs.base-branch }}" != "default" ]]; then
-            echo "❌ Invalid Branch: Check the input branch and base branch matches the pattern 'release.x.x.x'"
-            exit 1
-          fi
+#      - name: ✔️ Validate Inputs
+#        run: |
+#          pattern="^release-[0-9]+\.[0-9]+\.[0-9]+$"
+#
+#          if [[ ! "${{ inputs.release-branch }}" =~ $pattern ]] || \
+#          [[ ! "${{ inputs.base-branch }}" =~ $pattern && "${{ inputs.base-branch }}" != "default" ]]; then
+#            echo "❌ Invalid Branch: Check the input branch and base branch matches the pattern 'release.x.x.x'"
+#            exit 1
+#          fi
 
       - name: 🔑 Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v6
